version: '3'
services:
  app:
    build:
      context: ./docker/
      dockerfile: app.Dockerfile
    volumes:
      - .:/code
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "33063:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todolist
